-- Vista movida a reporting.vw_diario_documentos_pendientes_sap
-- Vista movida a reporting.vw_diario_documentos_pendientes_sap.
-- Este archivo se conserva solo como referencia histórica.
-- La capa de consumo debe usar reporting.vw_diario_documentos_pendientes_sap.
