-- Vistas movidas a reporting.flujo_dolares/07_view.sql.
-- Este archivo se conserva solo como referencia histórica.
-- La capa de consumo debe usar reporting.vw_flujo_dolares_variacion_transporte
-- y reporting.vw_flujo_dolares_por_proveedor.
